version: '3'

services:
  backend:
    image: python:3.11
    volumes:
      - ./backend:/app
    working_dir: /app
    command: >
      sh -c "pip install fastapi uvicorn &&
             uvicorn app:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"

  frontend:
    image: node:20
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: >
      sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
